<ul>
<li>Other High School</li>
<li>Academic Decathlon H.S.</li>
<li>Academic Literacy I - III H.S.</li>
<li>Accounting H.S.</li>
<li>Advanced Quantitative Reasoning H.S.</li>
<li>Adventure / Outdoor Education H.S.</li>
<li>Aerobic Activities H.S.</li>
<li>Aerobic Activities (STEP) H.S.</li>
<li>Aerospace Engineering (PLTW) H.S.</li>
<li>Ag Mechanics and Metal Technologies H.S.</li>
<li>Algebra I H.S.</li>
<li>Algebra II H.S.</li>
<li>American Sign Language I - III H.S.</li>
<li>American Studies H.S.</li>
<li>Anatomy and Physiology H.S.</li>
<li>Architectural Design H.S.</li>
<li>Art and Media Communications H.S.</li>
<li>Art H/AP Drawing Portfolio H.S.</li>
<li>Art H/AP Three-Dimensional Design H.S.</li>
<li>Art H/AP Two-Dimensional Design H.S.</li>
<li>Art History H.S.</li>
<li>Art I - III H.S.</li>
<li>Art Sculpture H.S.</li>
<li>Audio/Video Production - Advanced H.S.</li>
<li>Audio/Video Production (Video Technology) H.S.</li>
<li>Automotive Technology H.S.</li>
<li>All courses may not be offered 126 on every campus. H.S.</li>
<li>AVID I - IV H.S.</li>
<li>Band III - IV H H.S.</li>
<li>Baseball H.S.</li>
<li>Basketball H.S.</li>
<li>Bible Literacy H.S.</li>
<li>Biology H.S.</li>
<li>Business Information Management H.S.</li>
<li>Business Law H.S.</li>
<li>Calculus H.S.</li>
<li>Career Preparation I - II H.S.</li>
<li>Cheerleading H.S.</li>
<li>Chemistry H.S.</li>
<li>Child Development H.S.</li>
<li>Chinese I - IV H.S.</li>
<li>Choir III - IV H H.S.</li>
<li>College Reading Applications H.S.</li>
<li>Collision Repair and Refinishing H.S.</li>
<li>Communication Applications H.S.</li>
<li>Comparative Government H.S.</li>
<li>Computer Science H.S.</li>
<li>Concert Band I - IV H.S.</li>
<li>Concert Choir I - IV H.S.</li>
<li>Contemporary World Issues H.S.</li>
<li>Creative Writing H.S.</li>
<li>Cross Country H.S.</li>
<li>Culinary Arts H.S.</li>
<li>All courses may not be offered 127 on every campus. H.S.</li>
<li>Dance I - IV H.S.</li>
<li>Debate I - III H.S.</li>
<li>Digital and Interactive Media H.S.</li>
<li>Digital Design and Media Production (Desktop Publishing) H.S.</li>
<li>Diving H.S.</li>
<li>Dollars and Sense H.S.</li>
<li>Drill Team H.S.</li>
<li>Earth and Space Science H.S.</li>
<li>Economics, with Emphasis on the Free Enterprise System and Its
Benefits H.S.</li>
<li>Engineering Design and Presentation H.S.</li>
<li>Engineering Design and Problem Solving H.S.</li>
<li>English I H.S.</li>
<li>English I - II SOL (Speakers of Other Languages) H.S.</li>
<li>English II H.S.</li>
<li>English III H.S.</li>
<li>English IV H.S.</li>
<li>Entrepreneurship H.S.</li>
<li>Environmental Science H.S.</li>
<li>Environmental Systems H.S.</li>
<li>Equine Science H.S.</li>
<li>European History H.S.</li>
<li>Fashion Design H.S.</li>
<li>Fashion Marketing H.S.</li>
<li>Food Science H.S.</li>
<li>Football H.S.</li>
<li>All courses may not be offered 128 on every campus. H.S.</li>
<li>Forensic Science H.S.</li>
<li>Foundations of Personal Fitness H.S.</li>
<li>French I - V H.S.</li>
<li>Geometry H.S.</li>
<li>German I - IV H.S.</li>
<li>Global Business H.S.</li>
<li>Golf H.S.</li>
<li>Graphic Design and Illustration H.S.</li>
<li>Health I H.S.</li>
<li>Health Science H.S.</li>
<li>Health Science - Pharmacy Tech H.S.</li>
<li>Horticulture Science H.S.</li>
<li>Human Experience - Culture, Media and Perception H.S.</li>
<li>Human Geography H.S.</li>
<li>Humanities H.S.</li>
<li>Individual Sports H.S.</li>
<li>Instructional Practices in Education and Training H.S.</li>
<li>Integrated Physics and Chemistry (IPC) H.S.</li>
<li>Interior Design H.S.</li>
<li>Internetworking Technologies H.S.</li>
<li>Interpersonal Studies H.S.</li>
<li>Introduction to Engineering Design (PLTW) H.S.</li>
<li>Jazz / Show Choir I - IV H.S.</li>
<li>Jazz Band I - IV H.S.</li>
<li>All courses may not be offered 129 on every campus. H.S.</li>
<li>Journalism H.S.</li>
<li>Journalism - Independent Study H.S.</li>
<li>Junior Reserve Officer Training (JROTC) H.S.</li>
<li>Landscape Design and Turf Grass Management H.S.</li>
<li>Latin I - IV H.S.</li>
<li>Law Enforcement H.S.</li>
<li>Library Aide H.S.</li>
<li>Lifetime Nutrition and Wellness H.S.</li>
<li>Literary Genres H.S.</li>
<li>Livestock Production H.S.</li>
<li>Mapping for Academic and Personal Success (MAPS) H.S.</li>
<li>Marketing Dynamics H.S.</li>
<li>Math Independent Study H.S.</li>
<li>Mathematical Models with Applications H.S.</li>
<li>Medical Terminology H.S.</li>
<li>Mixed Choir I - IV H.S.</li>
<li>Music Theory H.S.</li>
<li>Newspaper I - II H.S.</li>
<li>Office Aide H.S.</li>
<li>Oral Interpretation I - III H.S.</li>
<li>Orchestra III - IV H H.S.</li>
<li>PAL - Peer Assistance and Leadership H.S.</li>
<li>Partners Physical Education H.S.</li>
<li>Peer Assistance for Students with Disabilities H.S.</li>
<li>Percussion Ensemble I - IV H.S.</li>
<li>All courses may not be offered 130 on every campus. H.S.</li>
<li>Philharmonic Orchestra I - IV H.S.</li>
<li>Photojournalism H.S.</li>
<li>Physics H.S.</li>
<li>Practicum in Agriculture, Food and Natural Resources H.S.</li>
<li>Floral Design H.S.</li>
<li>Veterinary Medicine H.S.</li>
<li>Practicum in Business Management H.S.</li>
<li>Practicum in Culinary Arts H.S.</li>
<li>Practicum in Education and Training H.S.</li>
<li>Practicum in Health Science H.S.</li>
<li>Practicum in Marketing Dynamics H.S.</li>
<li>Pre-Calculus H.S.</li>
<li>Principles and Elements of Floral Design H.S.</li>
<li>Principles of Business, Marketing and Finance H.S.</li>
<li>Principles of Engineering (PLTW) H.S.</li>
<li>Principles of Health Science H.S.</li>
<li>Principles of Hospitality and Tourism H.S.</li>
<li>Principles of Human Services H.S.</li>
<li>Principles of Information Technology H.S.</li>
<li>Principles of Law, Public Safety, Corrections and Security
H.S.</li>
<li>Professional Standards in Agribusiness H.S.</li>
<li>Psychology H.S.</li>
<li>Restaurant Management H.S.</li>
<li>Scientific Research and Design H H.S.</li>
<li>Small Animal Management H.S.</li>
<li>All courses may not be offered 131 on every campus. H.S.</li>
<li>Soccer H.S.</li>
<li>Sociology H.S.</li>
<li>Softball H.S.</li>
<li>Spanish I - V H.S.</li>
<li>Speech - Independent Study H.S.</li>
<li>Sports and Entertainment Marketing H.S.</li>
<li>Statistics H.S.</li>
<li>String Orchestra I - IV H.S.</li>
<li>Student Senate H.S.</li>
<li>Swimming H.S.</li>
<li>Symphonic Band I - IV H.S.</li>
<li>Syphony Orchestra I - IV H.S.</li>
<li>Team or Individual Sports (Weight Training) H.S.</li>
<li>Team Sport Officiating H.S.</li>
<li>Team Sports H.S.</li>
<li>Technical Theater I - IV H.S.</li>
<li>Technical Writing Research Study Skills H.S.</li>
<li>Tennis H.S.</li>
<li>Tenor / Bass Choir I - IV H.S.</li>
<li>Theater Arts I - IV H.S.</li>
<li>Theater Production I - IV H.S.</li>
<li>Touch System Data Entry H.S.</li>
<li>Track H.S.</li>
<li>Treble Choir I - IV H.S.</li>
<li>United States Government H.S.</li>
<li>United States History H.S.</li>
<li>Veterinary Medical Applications H.S.</li>
<li>All courses may not be offered 132 on every campus. H.S.</li>
<li>Video Game Design H.S.</li>
<li>Virtual Business H.S.</li>
<li>Visual Media and Analysis Production H.S.</li>
<li>Volleyball H.S.</li>
<li>Web Design (Web Mastering) H.S.</li>
<li>Wildlife, Fisheries and Ecology Management H.S.</li>
<li>Wind Ensemble I - IV H.S.</li>
<li>World Geography Studies H.S.</li>
<li>World History H.S.</li>
</ul>
<p>College-level Classes<br>
</p>
<ul>
<li>OTHER COLLEGE</li>
<li>3-D ANIMATION</li>
<li>ABNORMAL PSYCHOLOGY</li>
<li>ACADEMIC DISCOURSE</li>
<li>ACCOUNTING - INTERMEDIATE</li>
<li>ACOUSTICS OF MUSIC</li>
<li>ADVERTISING ACCOUNT MANAGEMENT</li>
<li>ADVERTISING ACCOUNT PLANNING</li>
<li>ADVERTISING CAMPAIGNS</li>
<li>ADVERTISING MEDIA</li>
<li>ADVERTISING RESEARCH</li>
<li>AESTH.EXPERIENCE&amp;JUDGMENT</li>
<li>AFRICAN AMERICAN IN US 1607-1877</li>
<li>AFRICAN CINEMA</li>
<li>AFRICAN DIASPORA</li>
<li>AIR FORCE LEADERSHIP</li>
<li>AIR POLLUTION MNGMT AND ENGR</li>
<li>ALGORITHM ENGINEERING</li>
<li>ALTERNATIVE ASSETS</li>
<li>AMER GOVT-POLITICS</li>
<li>AMERICAN FILM HISTORY</li>
<li>AMERICAN LITERARY HISTORY</li>
<li>AMERICAN POLITICAL THOUGHT</li>
<li>ANALOG &amp; DIGITAL CONTROL</li>
<li>ANALYSIS</li>
<li>ANATOMY &amp; PHYSIOLOGY</li>
<li>AND DRAMA HISTORY 1</li>
<li>AND THEORY OF PRINTS</li>
<li>ANGUAGE OTHER</li>
<li>ANIMAL RIGHTS</li>
<li>APEUTIC ACOUSTIC GUITAR</li>
<li>APPLICATION PROGRMMNG - ADVANCED</li>
<li>APPLIED MANAGEMENT SKILLS</li>
<li>APPLIED MOVEMENT</li>
<li>ARABIC</li>
<li>ARABIC - ADVANCED</li>
<li>ARABIC - BEGINNING</li>
<li>ARABIC - INTERMEDIATE</li>
<li>ARCHITECTURE</li>
<li>ARGUMENTATION AND ADVOCACY</li>
<li>ART AND ARCHITECTURE IN ITALY</li>
<li>ART AND CODE</li>
<li>ART AND CONTEXT: 1940-1970</li>
<li>ART HISTORY</li>
<li>ART IN PORTUGUESE EMPIRE</li>
<li>ART OF 3D MODELING &amp; ANIMATION</li>
<li>ART OF ACTING</li>
<li>ART OF FILM AND MEDIA</li>
<li>ARTS BUDGETING &amp; FINANCIAL MGT</li>
<li>ARTS MANAGEMENT</li>
<li>ASIAN RELIGIONS</li>
<li>ASSEMBLY LANGUAGE</li>
<li>ATION THEORY</li>
<li>ATTRACTING CAPITAL</li>
<li>AUDIT RISK AND CONTROLS</li>
<li>BASEBALL AND AMERICAN CULTURE</li>
<li>BASIC VIDEO &amp; AUDIO PRODUCTION</li>
<li>BASICS OF PHOTOGRAPHY</li>
<li>BIOCHEM STRUCTURE &amp; FUNCTION</li>
<li>BIOETHICS</li>
<li>BIOLOGICAL CHEMISTRY</li>
<li>BIOLOGICAL PSYCHOLOGY</li>
<li>BIOMECHANICS</li>
<li>BUDDHISM</li>
<li>BUSINESS &amp; PROFESSNL ASPECTS</li>
<li>BUSINESS AND JOURNALISM</li>
<li>BUSINESS COMMUNICATIONS&amp; LEADER DEV</li>
<li>BUSINESS ETHICS</li>
<li>BUSINESS LAW</li>
<li>BUSINESS MODELING W/ SPREADSHEETS</li>
<li>BUSINESS MODELING W/SPREADSHTS</li>
<li>BUSINESS OF ENERGY</li>
<li>BUSINESS WRITING</li>
<li>C SYNTHESIS</li>
<li>CAD</li>
<li>CAD</li>
<li>CALCULUS</li>
<li>CALCULUS BUSINESSI-SOCIAL SC</li>
<li>CANCER BIOLOGY</li>
<li>CERAMICS</li>
<li>CHAMBER ENSEMBLE: GUITAR</li>
<li>CHAMBER ENSEMBLE: KEYBOARD</li>
<li>CHAMBER ENSEMBLE: PIANO DUOS</li>
<li>CHAMBER ENSEMBLE: SONATAS</li>
<li>CHAMBER ENSEMBLE: STRINGS</li>
<li>CHAMBER ENSEMBLE: VOICE</li>
<li>CHAMBER ENSEMBLE: WINDS &amp; PERC</li>
<li>CHEM FOR LIBERAL ARTS</li>
<li>CHINA BEFORE 1850</li>
<li>CHINESE</li>
<li>CHINESE - ADVANCED</li>
<li>CHINESE - BEGINNING</li>
<li>CHINESE - INTERMEDIATE</li>
<li>CHINESE POLITICS</li>
<li>CHRISTIANITY/PUBLIC LIFE</li>
<li>CHRISTIANTY&amp; THE BIBLE</li>
<li>CIRCUIT ANALYSIS</li>
<li>CIVIL &amp; ENVIR ENGR</li>
<li>CIVIL AND ENVIRO ENGR DESIGN</li>
<li>CIVIL LIBERTIES:1ST AMENDMENT</li>
<li>CIVIL RIGHTS</li>
<li>CLASS GUITAR</li>
<li>CLASS PIANO</li>
<li>CLASS PIANO - ADVANCED</li>
<li>CLASS PIANO - BEGINNING</li>
<li>CLASS VOICE</li>
<li>CLOSE RELATIONSHIPS</li>
<li>COL ORATIVE COMPOSITION</li>
<li>COLOR PHOTOGRAPHY</li>
<li>COMM RESEARCH AND METRICS</li>
<li>COMM. IN GLOBAL CONTEXTS</li>
<li>COMMERCIAL FRENCH</li>
<li>COMMERCIAL SPANISH</li>
<li>COMMUNICATION AND INFO SYSTEMS</li>
<li>COMMUNICATION ETHICS</li>
<li>COMMUNICATION LAW</li>
<li>COMMUNITY ENGAGEMENT</li>
<li>COMPARATIVE GRAMMAR</li>
<li>COMPARATIVE POLITICS</li>
<li>COMPOSITION STUDIES</li>
<li>COMPUTATIONAL PHYSICS</li>
<li>COMPUTATIONAL SCULPTURE</li>
<li>COMPUTER ARCHITECTURE</li>
<li>COMPUTER NTWKS &amp; DISTR SYSTEMS</li>
<li>COMPUTER SIMULATION TECH</li>
<li>COMPUTER SYSTEM SECURITY</li>
<li>COMPUTERS &amp; INFO TECH</li>
<li>COMPUTING CONCEPTS</li>
<li>CONCEPTING</li>
<li>CONCEPTS OF EVOLUTION</li>
<li>CONCEPTS OF EVOLUTION: A HIST</li>
<li>CONCERT CHOIR</li>
<li>CONCRETE DESIGN - ADVANCED</li>
<li>CONSOLIDATED CALCULUS</li>
<li>CONSUMER BEHAVIOR</li>
<li>CONTEMPORARY APPROACHES TO LIT</li>
<li>CONTEMPORARY ARCHAEOLOGY</li>
<li>CONTEMPORARY GERMAN CULTURE</li>
<li>CONTEMPORARY ISSUES</li>
<li>CONTEMPORARY MARKETS &amp; CULTURE</li>
<li>CONTEMPORARY MORAL PROBLEMS</li>
<li>CONTENT AREA METHODS</li>
<li>CONTENT AREA STUDIES FOR ELEM</li>
<li>CONTEXTS OF DISABILITY</li>
<li>CONTROL</li>
<li>COOP ED IN AEROSPACE STUDIES</li>
<li>CORP SOCIAL RESPONSIBILITY</li>
<li>CORPORATE SOCIAL RESPONSIBILTY</li>
<li>COST ACCOUNTING</li>
<li>COST-BENEFIT ANALYSIS</li>
<li>COSTUM RUNNING/CONST CREW</li>
<li>COSTUME DESIGN</li>
<li>COSTUME PRACTICUM</li>
<li>CRAFTY WORLDS</li>
<li>CREATIVE COMP. MAJOR CAPSTONE</li>
<li>CREATIVE COMP. MINOR CAPSTONE</li>
<li>CREATIVE PRODUCTION</li>
<li>CREATIVE WRITING</li>
<li>CREATIVITY</li>
<li>CRISIS MANAGEMENT</li>
<li>CRITICAL ISSUES</li>
<li>CRITICAL STUDIES SEMINAR</li>
<li>CRITICAL THINKING</li>
<li>CULT &amp; ETHIC IMPLIC OF TECH</li>
<li>CULTURAL ANTHROPOLOGY</li>
<li>CULTURAL ASPECTS OF BUSINESS</li>
<li>CULTURAL DIALOGUES: LATIN AMER</li>
<li>CULTURAL DIALOGUES: SPAIN</li>
<li>CULTURE &amp; DIVERSITY IN AMERICA</li>
<li>CULTURE IN THE U.S.</li>
<li>CULTURE, GRAMMAR, &amp; LITERATURE</li>
<li>D THE WEST</li>
<li>DANCE COMPOSITION</li>
<li>DANCE HISTORY I: BALLET</li>
<li>DANCE PRODUCTION</li>
<li>DANCER'S TOOLBOX</li>
<li>DATA STRUCTURES</li>
<li>DATABASE CONCEPTS</li>
<li>DATABASE METHODS AND ANALYSIS</li>
<li>DECISION-MAKING</li>
<li>DEPARTMENTAL DISTINCTION</li>
<li>DEPARTMENTAL SEMINARS</li>
<li>DESIGN AND ANALYSIS</li>
<li>DESIGN OF STEEL STRUCTURES</li>
<li>DESIGN&amp;CONTROL-MECH SYSTM</li>
<li>DEVELOPING ARTS VENTURE PLAN</li>
<li>DEVELOPMENTAL MUSIC THRPY</li>
<li>DEVELOPMENTAL PSYCHOLOGY</li>
<li>DEVELOPMENTL MUTY PRACT</li>
<li>DICTION - ENGLISH</li>
<li>DICTION - ITALIAN</li>
<li>DIFFERENTIAL EQUATIONS</li>
<li>DIGITAL COMMUNICATION</li>
<li>DIGITAL COMPUTER DESIGN</li>
<li>DIGITAL COMPUTER LOGIC</li>
<li>DIGITAL HYBRID MEDIA</li>
<li>DIGITAL IMAGE PROCESSING</li>
<li>DIGITAL JOURNALISM</li>
<li>DIGITAL LOGIC DESIGN</li>
<li>DIGITAL MEDIA LANDSCAPES</li>
<li>DIGITAL SYSTEMS DESIGN</li>
<li>DIR STUD IN MUSIC HISTORY</li>
<li>DIR STUDIES - COMPOSITION</li>
<li>DIR STUDIES IN MUSIC EDUC</li>
<li>DIRECTED READINGS &amp; RESEARCH</li>
<li>DIRECTED STUDIES</li>
<li>DIRECTED STUDIES--PERFORM</li>
<li>DIRECTED STUDIES-PERFORMANCE</li>
<li>DIRECTED STUDY</li>
<li>DIRECTING 1</li>
<li>DIRECTING 3</li>
<li>DISCRETE COMP STRUCTURES</li>
<li>DISTINCTION SEMINAR IN PSYC</li>
<li>DOING THINGS WITH POEMS</li>
<li>DRAMATIC ARTS TODAY</li>
<li>DRAWING</li>
<li>DRAWING: INTERMEDIATE LEVEL</li>
<li>DRUGS AND BEHAVIOR</li>
<li>DSP PROGRAMMING</li>
<li>DYNAMICS</li>
<li>Descr</li>
<li>EARTH AND LIFE</li>
<li>EARTH MATERIALS I: MINERALOGY</li>
<li>EARTH SYSTEMS</li>
<li>EARTHQUAKES AND VOLCANOES</li>
<li>ECON AND BUSINESS FORECASTING</li>
<li>ECON DEVELOPMENT: MICRO</li>
<li>ECONOMIC DEVELOPMENT: MACRO</li>
<li>ECONOMICS OF HUMAN RESOURCES</li>
<li>ECONOMICS PRACTICUM</li>
<li>EDITING</li>
<li>EDITORIAL/OPINION WRITING</li>
<li>EDUCATIONAL PSYCHOLOGY</li>
<li>EE : ELECTRON CIRC</li>
<li>EE : ELECTRONIC CIRC</li>
<li>ELECTRICITY &amp; MAGNETISM</li>
<li>ELECTRICITY AND MAGNETISM</li>
<li>ELECTRO-ACOUSTIC MUSIC</li>
<li>ELECTROMAG RAD + ANTENNAS</li>
<li>ELECTRONIC CIRCUITS</li>
<li>ELEMENTARY LOGIC</li>
<li>ELEMENTARY MUSIC METHODS</li>
<li>ELEMENTARY MUSIC PRACTICUM</li>
<li>ELEMENTARY STUDENT TEACHING</li>
<li>ELEMENTS MECHANICAL DSGN</li>
<li>ELEMENTS OF ASTRONOMY</li>
<li>EMATICAL MODELING</li>
<li>EMATICAL STATISTICS</li>
<li>EMBEDDED WIRELESS DESIGN</li>
<li>EMERGENT LITERACY</li>
<li>EMPLOYEE BENEFITS</li>
<li>ENGINEERING</li>
<li>ENGINEERING AND BEYOND</li>
<li>ENGINEERING COMMUNICATIONS</li>
<li>ENGINEERING DESIGN</li>
<li>ENGINEERING ECONOMY</li>
<li>ENGINEERING INTERNSHIP</li>
<li>ENGINEERING MANAGEMENT</li>
<li>ENGINEERING MATERIALS</li>
<li>ENSEMBLE PERFORMANCE</li>
<li>ENSEMBLE PERFORMANCE IV</li>
<li>ENSEMBLE PERFORMANCE V</li>
<li>ENTREPRENEURSHIP</li>
<li>ENVIR ENGR PRINC AND PROCESSES</li>
<li>ENVIRON ENGR &amp; SC</li>
<li>ENVIRON TOXICOLOGY</li>
<li>ENVIRONMENTAL &amp; ENERGY POLICY</li>
<li>ENVIRONMENTAL POLICY</li>
<li>ENVIRONMENTAL SCIENCE</li>
<li>ENVIRONMENTAL TOXICOLOGY</li>
<li>ENVIRONMENTL CHEM/BIOLOGY</li>
<li>EORY</li>
<li>EORY IV</li>
<li>ERAPY</li>
<li>ERAPY PRACTCM V</li>
<li>ESL COMMUNICATION SKILLS</li>
<li>ESL PRONUNCIATION SKILLS</li>
<li>ESSENTIALS</li>
<li>ESSENTIALS OF BIOLOGY</li>
<li>ETHICS</li>
<li>ETHICS OF COVERGENT MEDIA</li>
<li>EUROPE IN MOD WORLD, 1760-PRES</li>
<li>EV THEORY &amp; PRACTICE</li>
<li>EVOL OF AMERICAN CAPITALISM</li>
<li>EVOL/USAF AIR &amp; SPACE POWER</li>
<li>EXERCISE PHYSIOLOGY</li>
<li>EXERCISE PHYSIOLOGY WITH</li>
<li>EXPERIMENTAL CAMERA</li>
<li>EXPERIMENTAL STATISTICS</li>
<li>F THE EARTH</li>
<li>FACE-1ST YR ARTS COMMUNITY EXP</li>
<li>FAMILY IN EUROPEAN PAINTING</li>
<li>FANTASTIC ARCHAEOLOGY</li>
<li>FASHION JOURNALISM</li>
<li>FASHION PHOTOGRAPHY</li>
<li>FASHION, MEDIA, AND CULTURE</li>
<li>FICTION</li>
<li>FIELD EXPERIENCE I: ELEMENTARY</li>
<li>FIELD EXPERIENCE I: SECONDARY</li>
<li>FIELD EXPERIENCE II: SECONDARY</li>
<li>FIELD EXPERIENCE II:ELEMENTARY</li>
<li>FIELD EXPERIENCE III: ELEMNTRY</li>
<li>FIELD EXPERIENCE III:SECONDARY</li>
<li>FILE ORGANIZATION DATABASE MGT</li>
<li>FILM ACTING</li>
<li>FILM AND TELEVISION GENRES</li>
<li>FILM EXHIBITION &amp; DISTRIBUTION</li>
<li>FILM, CULTURE AND SOCIETY</li>
<li>FIN ECO AND INVESTMENT BEH</li>
<li>FINANCIAL ACCOUNTING</li>
<li>FINANCIAL ACCOUNTING &amp; REPORTING</li>
<li>FINANCIAL MANAGEMENT</li>
<li>FINANCIAL MANAGEMENT - ADVANCED</li>
<li>FIRST YEAR SEMINAR</li>
<li>FITNESS AND HEALTH ENTERPRISE</li>
<li>FLUID MECHANICS</li>
<li>FORENSIC PSYCHOLOGY</li>
<li>FORENSICS WORKSHOP</li>
<li>FORM AND ANALYSIS</li>
<li>FORMATIVE/SUMMATIVE ASSESSMENT</li>
<li>FOUNDATIONS OF ESL INSTRUCTION</li>
<li>FOUNDATIONS OF FINANCIAL ECO</li>
<li>FOUNDATIONS OF LEADERSHIP</li>
<li>FOUNDATIONS OF POLIT THOUGHT</li>
<li>FOUNDATIONS-WRITTEN&amp;ORAL DISC.</li>
<li>FREE SPEECH &amp; FIRST AMENDMENT</li>
<li>FREN II WITH REVIEW - BEGINNING</li>
<li>FREN LITERATURE TO REVOLUTION</li>
<li>FRENCH</li>
<li>FRENCH - ADVANCED</li>
<li>FRENCH - BEGINNING</li>
<li>FRENCH - INTERMEDIATE</li>
<li>FRENCH HIST &amp; CULTURE</li>
<li>FRENCH LIT TEXTS</li>
<li>FRENCH PHONICS</li>
<li>FULL-TIME STATUS</li>
<li>FUND OF INSTRMNTL CONDUCT</li>
<li>FUND OF PIANO PEDAGOGY</li>
<li>FUNDAMENTALS OF AIR QUALITY</li>
<li>FUNDAMENTALS OF ALGORITHMS</li>
<li>FUNDAMENTALS OF AUDIO &amp; SOUND</li>
<li>FUNDAMENTALS OF MARKETING</li>
<li>FUNDTL OF CHORAL CONDUCT</li>
<li>GENDER AND GLOBALIZATION</li>
<li>GENDER AND HUMAN RIGHTS</li>
<li>GENDER AND SEX ROLES</li>
<li>GENDER:IMAGES AND PERSPECTIVES</li>
<li>GENERAL CHEMISTRY</li>
<li>GENERAL PHYSICS</li>
<li>GENETIC DETERMINISM &amp;FREE WILL</li>
<li>GENETICS</li>
<li>GENOMICS AND BIOINFORMATICS</li>
<li>GERMAN</li>
<li>GERMAN - BEGINNING</li>
<li>GHTS &amp; THE JOURNALIST</li>
<li>GLOBAL ENERGY MARKETS</li>
<li>GLOBAL ENGAGEMENT</li>
<li>GLOBAL SOCIETY</li>
<li>GRAPHIC DESIGN STUDIO</li>
<li>GRAPHICAL USER INTERFACE</li>
<li>GRD WTR HYDRO &amp; CONTAMNT</li>
<li>GUITAR REPERTOIRE</li>
<li>GY OF THE FAMILY</li>
<li>HAND DRUM/ETHNIC PERCUSSION</li>
<li>HARPSICHORD</li>
<li>HDW SECURITY &amp;TROJAN DETECTION</li>
<li>HE EARTH</li>
<li>HE WORLD</li>
<li>HEALTH IN CROSS-CULTURAL PERSP</li>
<li>HEALTH PSYCHOLOGY</li>
<li>HEAT AND MASS TRANSFER</li>
<li>HEAT TRANSFER</li>
<li>HESIS IN COMMUNICATION</li>
<li>HETIC EXPERIENCE &amp; JUDGMNT</li>
<li>HIGHWAYS DESIGN AND SAFETY</li>
<li>HINDI - BEGINNING</li>
<li>HIST OF RELIGIONS IN AMERICA</li>
<li>HIST WESTRN PHIL-ANCIENT</li>
<li>HIST+METH OF HIST OF ART</li>
<li>HISTORY OF ANCIENT GREECE</li>
<li>HISTORY OF ANTHROPOLOGY PART 1</li>
<li>HISTORY OF DESIGN</li>
<li>HISTORY OF ISLAMIC EMPIRES</li>
<li>HISTORY OF JOURNALISM</li>
<li>HISTORY OF MEXICO</li>
<li>HISTORY OF MODERN GERMANY</li>
<li>HISTORY OF MODERN PHILOSOPHY</li>
<li>HISTORY OF PHOTOGRAPHY</li>
<li>HISTORY OF PSYCHOLOGY</li>
<li>HISTORY OF SOUTH AFRICA</li>
<li>HOLOCAUST</li>
<li>HONORS HUMANITIES SEMINAR</li>
<li>HUMAN DIVERSITY</li>
<li>HUMAN ECOLOGY</li>
<li>HUMAN EVOLUTION</li>
<li>HUMAN RESOURCES MANAGEMENT</li>
<li>HUMAN RIGHTS:AMER DILEMMA</li>
<li>HUMAN RIGHTS:AMER.DILEMMA</li>
<li>HUMAN RIGHTS:AMERICA'S DILEMMA</li>
<li>HUMAN SEXUALITY</li>
<li>IC CATHEDRAL</li>
<li>IDEAS OF MODERN PHYSICS</li>
<li>IDENTIFYING ENTREPRENEUR</li>
<li>IDENTITY IN AFRICAN CINEMA</li>
<li>IMAGINATION AND INTERPRETATION</li>
<li>IMAGINATION/CAPTL PUNISHMENT</li>
<li>IMAGINED COMMUNITIES</li>
<li>IN LITERARY THEORY</li>
<li>IN THE U.S.</li>
<li>IN THE US SINCE 1865</li>
<li>INDEPENDENT STUDY</li>
<li>INDEPENDENT STUDY IN APSM</li>
<li>INDEPENDENT STUDY IN ECONOMICS</li>
<li>INDIANS OF NORTH AMERICA</li>
<li>INDIVIDUAL/TEAM DEVELOPMENT</li>
<li>INDUSTRIALISM &amp; REFORM IN US</li>
<li>INFO SYSTEM DESIGN STRATEGIES</li>
<li>INFORM ENG &amp; GLOBAL PERSP</li>
<li>INFORMATION SYSTEMS FOR MGMT</li>
<li>INFORMATION TECH &amp; SOCIETY</li>
<li>INORGANIC CHEMISTRY - ADVANCED</li>
<li>INQUIRY SEMINAR</li>
<li>INSTRUMENT PEDAGOGY</li>
<li>INSTRUMENTATION AND ARRANGING</li>
<li>INTEGRATED MKTG COMMUNICATIONS</li>
<li>INTEGRATING TEACH/LEARN</li>
<li>INTERM FLUID DYNAMICS</li>
<li>INTERMEDIATE ACCOUNTING</li>
<li>INTERMEDIATE ARABIC</li>
<li>INTERMEDIATE CHINESE</li>
<li>INTERMEDIATE FRENCH</li>
<li>INTERMEDIATE ITALIAN-1ST SEM</li>
<li>INTERMEDIATE JAPANESE</li>
<li>INTERMEDIATE MACROECONOMICS</li>
<li>INTERMEDIATE SPANISH</li>
<li>INTERNATIONAL FILM HISTORY</li>
<li>INTERNATIONAL FINANCE</li>
<li>INTERNATIONAL MARKETING</li>
<li>INTERNATIONAL TRADE</li>
<li>INTERNATIONL POLITICAL ECONOMY</li>
<li>INTERNATL RELATIONS</li>
<li>INTERNSHIP</li>
<li>INTERNSHIP I: EC û6</li>
<li>INTERNSHIP I: HS &amp; MS</li>
<li>INTERNSHIP II: ECû6</li>
<li>INTERNSHIP II: HS &amp; MS</li>
<li>INTERNSHIP IN ETHNIC STUDIES</li>
<li>INTERNSHIP IN FRENCH</li>
<li>INTERNSHIP IN HISTORY</li>
<li>INTERNSHIP IN INTL</li>
<li>INTERNSHIP IN LAAM</li>
<li>INTERNSHIP IN MUSIC</li>
<li>INTRO TO STAT COMPUTING</li>
<li>INTRODUCTORY BIOLOGY</li>
<li>INTRODUCTORY ECONOMETRICS</li>
<li>INTRODUCTORY MECHANICS</li>
<li>INVENTING AMERICAS</li>
<li>INVESTMNT ANALYSIS&amp; PTFLO MGMT</li>
<li>ITAL AUTHORS-CONTEMPORARY</li>
<li>ITALIAN</li>
<li>ITALIAN - BEGINNING</li>
<li>ITALIAN CULTURE</li>
<li>ITALIAN-1ST SEM - INTERMEDIATE</li>
<li>ITALIAN-2ND SEM - BEGINNING</li>
<li>JAPANESE</li>
<li>JAPANESE - BEGINNING</li>
<li>JAPANESE - INTERMEDIATE</li>
<li>JAZZ DANCE</li>
<li>JAZZ: TRADITION/TRANSFORM</li>
<li>JEWISH AMERICAN LITERATURE</li>
<li>JEWISH-AM LITERATURE&amp;CULTURE</li>
<li>JFK:LIFE,TIMES,&amp;LEGEND</li>
<li>JNR SEMINAR RESEARCH&amp;WRITING</li>
<li>JUNIOR RECITAL</li>
<li>KINESIOLOGY FOR DANCE</li>
<li>LAAM DIRECTED STUDIES</li>
<li>LANGUAGE IN CULTURE &amp; SOCIETY</li>
<li>LATIN</li>
<li>LATIN - BEGINNING</li>
<li>LATIN AMERICA</li>
<li>LATIN: MYTH VIA OVID - ADVANCED</li>
<li>LAW</li>
<li>LAW AND ECONOMICS</li>
<li>LEADERSHIP</li>
<li>LEADERSHIP - ADVANCED</li>
<li>LEADING AND MANAGING</li>
<li>LEARNING ENV/PROF EC-12</li>
<li>LEGAL &amp; ETHICAL ASPECTS APSM</li>
<li>LEVEL - INTERMEDIATE</li>
<li>LIGHT RUNNING/CONSTR CREW</li>
<li>LIGHTING DESIGN</li>
<li>LIGHTING PRACTICUM</li>
<li>LINEAR ALGEBRA</li>
<li>LIT OF RELIGIOUS REFLECTION</li>
<li>LITERACY AND SOCIETY</li>
<li>LITERARY JOURNALISM</li>
<li>LITERARY STUDY</li>
<li>LITERATURE AND CULTURE</li>
<li>LITERATURE OF MINORITIES</li>
<li>LOW BRASS TECHNIQUES</li>
<li>LUS MATHEMATICS</li>
<li>MACHINES &amp; SOCIETY</li>
<li>MACROECONOMICS - INTERMEDIATE</li>
<li>MAGAZINE WRITING</li>
<li>MAL SYSTEMS DESIGN</li>
<li>MANAGEMENT</li>
<li>MANAGEMENT OF INFO TECH</li>
<li>MANAGEMENT SCIENCE</li>
<li>MANAGERIAL ACCOUNTING</li>
<li>MANAGERIAL STATISTICS</li>
<li>MANUFACTURING PROCESSES</li>
<li>MAPPING MODERNISM</li>
<li>MARKETING ENGINEERING</li>
<li>MARKETING INTERNSHIP</li>
<li>MARKETING MANAGEMENT</li>
<li>MARKETING PRINCIPLES OF ADV</li>
<li>MARKETING RESEARCH</li>
<li>MARKETS AND CULTURE</li>
<li>MARRIAGE AND FAMILY</li>
<li>MATH SCIENCES</li>
<li>MATRIX STRUCTURE ANALYSIS</li>
<li>MCI: COMM CONSULTING</li>
<li>MCII: CAPSTONE</li>
<li>MEADOWS CHORALE</li>
<li>MEADOWS JAZZ ORCHESTRA</li>
<li>MEADOWS OPERA ENSEMBLE</li>
<li>MEADOWS OPERA WORKSHOP</li>
<li>MEADOWS PERCUSSION ENSEMBLE</li>
<li>MEADOWS SYMPHONY ORCHESTRA</li>
<li>MEADOWS UG FT STATUS</li>
<li>MEADOWS WIND ENSEMBLE</li>
<li>MECH OF DEFORMABLE BODIES</li>
<li>MECHANICAL ENG DESIGN</li>
<li>MECHANICS</li>
<li>MECHANICS OF DEFORMABLE BODIES</li>
<li>MECHANICS OF MATERIALS</li>
<li>MEDIA AND CULTURE</li>
<li>MEDIA ARABIC - ADVANCED</li>
<li>MEDIA THEORY</li>
<li>MEDICAL ANTHROPOLOGY</li>
<li>MEDICINAL CHEMISTRY</li>
<li>MEDIEVAL WORLD: 306 TO 1095</li>
<li>MEMORY AND COGNITION</li>
<li>MEN'S BALLET TECHNIQUE</li>
<li>METAPHYSICS</li>
<li>METEOROLOGY</li>
<li>METHODS AND TECH FOR SUSTAIN</li>
<li>MEXICAN AMERICANS:1848-PRESENT</li>
<li>MGMT OF FINANCIAL INSTITUTIONS</li>
<li>MICROBIOLOGY</li>
<li>MINORITY-DOMINANT RELATIONS</li>
<li>MIRRORING LINE</li>
<li>MOD ELECTRONIC TECHNOLOGY</li>
<li>MODERN DANCE</li>
<li>MODERN DANCE - BEGINNING</li>
<li>MODERN ELECTIVE - ADVANCED</li>
<li>MODERN PHYSICS</li>
<li>MODYNAMICS</li>
<li>MOLECULAR BIOLOGY</li>
<li>MOLECULAR GENETICS</li>
<li>MONEY AND BANKING</li>
<li>MONEY AND CAPITAL MARKETS</li>
<li>MONKEYS &amp; APES</li>
<li>MUSIC EDUCATION</li>
<li>MUSIC HISTORY REVIEW</li>
<li>MUSIC PATHWAYS</li>
<li>MUSIC: ART OF LISTENING</li>
<li>MUSIC: CONTEMP AUDIENCES</li>
<li>MUSICAL ACOUSTICS</li>
<li>MUSICIANSHIP</li>
<li>MUSICIANSHIP - ADVANCED</li>
<li>MUSICIANSHIP IV</li>
<li>MUSTANG MARCHING BAND</li>
<li>MUSTANG STRINGS</li>
<li>N AMER MUSICAL THEATRE</li>
<li>NATIONAL SECURITY FORCES</li>
<li>ND THE COLD WAR</li>
<li>NEGOTIATIONS</li>
<li>NEW TESTAMENT</li>
<li>NOMICS: THEORY&amp; POLICY</li>
<li>NON-WESTERN CULT AND LIT</li>
<li>NONFICTION PRODUCTION</li>
<li>NONPARAMETRIC STATISTICS</li>
<li>NORITIES IN THE MEDIA</li>
<li>NOVEL, POST-CIVIL WAR</li>
<li>NUMERICAL ANALYSIS</li>
<li>NUTRITION</li>
<li>O THE 19TH CENTURY</li>
<li>O.R.A.C.L.E.</li>
<li>OBSERVATION</li>
<li>OCEANOGRAPHY</li>
<li>OF SOUTHEAST ASIA</li>
<li>OF THE CRUSADES</li>
<li>OF THEORETICAL PHYSICS</li>
<li>ONS OF THE USAF</li>
<li>OPER SYS AND SYS SOFTWARE</li>
<li>OPERATIONS MANAGEMENT</li>
<li>OPERATIONS RESEARCH</li>
<li>OR ECONOMICS</li>
<li>ORAL COMMUNICATION</li>
<li>ORCH REP - STRINGS</li>
<li>ORCHESTRAL REP - PERCUSSION</li>
<li>ORCHESTRAL REP-PERCUSSION</li>
<li>ORGANIC CHEMISTRY</li>
<li>ORGANIZATIONAL PSYCHOLOGY</li>
<li>ORGANIZATIONS IN LOCAL CONTEXT</li>
<li>ORIGINS OF CIVILIZATION</li>
<li>OUT OF MANY:US HISTORY TO 1877</li>
<li>PAINTING</li>
<li>PAINTING - ADVANCED</li>
<li>PAINTING INTERMEDIATE</li>
<li>PARASITOLOGY</li>
<li>PARTNERING</li>
<li>PARTNERING I</li>
<li>PAS DE DEUX</li>
<li>PDE</li>
<li>PERCUSSION TECHNIQUES</li>
<li>PERSONALITY</li>
<li>PETROLEUM GEOLOGY</li>
<li>PHIL OF LANGUAGE</li>
<li>PHILOSOPHY</li>
<li>PHILOSOPHY OF BIOLOGY</li>
<li>PHILOSOPHY OF LAW</li>
<li>PHOTOGRAPHIC BOOK</li>
<li>PHOTOJOURNALISM</li>
<li>PHYSICAL CHEMISTRY</li>
<li>PHYSICAL CHEMISTRY - ADVANCED</li>
<li>PHYSICAL CHEMISTRY OF PROTEINS</li>
<li>PHYSICS OF MUSIC</li>
<li>PHYSIOLOGY</li>
<li>PIANO PED INTERNSHIP</li>
<li>PIANO PEDAGOGY PRACTICUM</li>
<li>PIANO REPERTOIRE</li>
<li>PILATES</li>
<li>PLAYWRITING 1</li>
<li>PLAYWRITING 3</li>
<li>POETRY</li>
<li>POLITICS &amp; THE BUDGET</li>
<li>POLITICS OF CHANGE</li>
<li>POLITICS OF CHANGE IN AMERICA</li>
<li>POLITICS OF MILITARY FORCE</li>
<li>PORTFOLIO</li>
<li>PORTFOLIO - ADVANCED</li>
<li>PORTFOLIO MANAGEMENT PRACTICUM</li>
<li>PR IN LOCAL CONTEXTS</li>
<li>PR IN SPORT - ADVANCED</li>
<li>PRACTICUM IN COL PERF</li>
<li>PRACTICUM:GROUP LEADERSHIP</li>
<li>PRE-LAW SCHOLARS SEMINAR</li>
<li>PRECALCULUS FOR BUSINESS</li>
<li>PRIN: INFLATION, RECESSION</li>
<li>PRINCIPLES OF COMPUTER SCIENCE</li>
<li>PRINCIPLES OF MICROECONOMICS</li>
<li>PRINCIPLES OF PUBLIC POLICY</li>
<li>PRINCIPLES OF RISK MGMT</li>
<li>PRINTMAKING</li>
<li>PRINTMAKING WORKSHOP</li>
<li>PRIVATE COMPOSITION</li>
<li>PRIVATE STUDY: BASSOON</li>
<li>PRIVATE STUDY: CELLO</li>
<li>PRIVATE STUDY: CLARINET</li>
<li>PRIVATE STUDY: EUPHONIUM</li>
<li>PRIVATE STUDY: FLUTE</li>
<li>PRIVATE STUDY: GUITAR</li>
<li>PRIVATE STUDY: HARP</li>
<li>PRIVATE STUDY: OBOE</li>
<li>PRIVATE STUDY: ORGAN</li>
<li>PRIVATE STUDY: PERCUSSION</li>
<li>PRIVATE STUDY: PIANO</li>
<li>PRIVATE STUDY: SAXOPHONE</li>
<li>PRIVATE STUDY: TROMBONE</li>
<li>PRIVATE STUDY: TRUMPET</li>
<li>PRIVATE STUDY: TUBA</li>
<li>PRIVATE STUDY: VIOLA</li>
<li>PRIVATE STUDY: VIOLIN</li>
<li>PRIVATE STUDY: VOICE</li>
<li>PRIVATE STUDY:DOUBLE BASS</li>
<li>PRIVATE STUDY:FRENCH HORN</li>
<li>PRIVATE STUDY:HARPSICHORD</li>
<li>PROBLEMS IN AMERICAN HISTORY</li>
<li>PROBLEMS IN EUROPEAN HISTORY</li>
<li>PROBLEMS IN FRENCH LITERATURE</li>
<li>PROBLEMS IN MIDDLE EAST HIST</li>
<li>PROD FOR NON-CREATIVE TRACK</li>
<li>PRODUCERS SEMINAR</li>
<li>PRODUCTION 1</li>
<li>PRODUCTION 2</li>
<li>PRODUCTION SYSTEMS ENGINEERING</li>
<li>PROFESSIONAL SEMINAR</li>
<li>PROGRAM AND PROJECT MANAGEMENT</li>
<li>PROGRAMMING CONCEPTS</li>
<li>PROGRAMMING LANGUAGES</li>
<li>PROJECT MANAGEMENT</li>
<li>PSYCHIATRIC MUTY PRACT</li>
<li>PSYCHOLOGICAL DISORDERS</li>
<li>PSYCHOLOGY</li>
<li>PSYCHOLOGY OF RELIGION</li>
<li>PSYCHOLOGY OF WOMEN</li>
<li>PUB OPINION &amp; AMER POLITICS</li>
<li>PUBLIC FINANCE</li>
<li>PUBLIC OPINION, PRESS &amp; POLICY</li>
<li>PUBLIC RELATIONS</li>
<li>PUBLIC RELATIONS MANAGEMENT</li>
<li>PUBLIC SPEAKING IN CONTEXT</li>
<li>PURITAN TRADITION</li>
<li>QUANTITATIVE ANALYSIS</li>
<li>QUANTITATIVE REASONING</li>
<li>QUANTUM MECHANICS</li>
<li>R THE STAGE</li>
<li>R THE STAGE 1</li>
<li>R THE STAGE 3</li>
<li>R THE STAGE 5</li>
<li>RACE AND ETHNICITY IN US</li>
<li>RACE/GENDER IN VISUAL CULTURE</li>
<li>RANDOM PROCESSES IN ENGRG</li>
<li>READINGS IN SPANISH - ADVANCED</li>
<li>REAL ESTATE FUNDAMENTALS</li>
<li>REAL ESTATE VALUATION</li>
<li>RECITAL ATTENDANCE</li>
<li>RENAISSANCE/GOLDEN AGE PROSE</li>
<li>REPORTING</li>
<li>REPUBLICANISM &amp; GOOD SOCIETY</li>
<li>RESEARCH</li>
<li>RESEARCH METHODS IN PSYCHOLOGY</li>
<li>RESEARCH PRACTICUM AP</li>
<li>REV EXPER IN RUSSIA:1900-1930</li>
<li>REVENUE IN SPORTS</li>
<li>RHETORIC, COMMUNITY &amp; PUB DEL</li>
<li>RIC MUSIC THERAPY</li>
<li>RISE OF CHRISTIANITY</li>
<li>RUSS READING &amp; CONVERSATN</li>
<li>RUSSIAN</li>
<li>RUSSIAN - BEGINNING</li>
<li>RY OF DIG DATA PROC GEOPHY</li>
<li>RY OF INDUSTRIAL STRUCTURE</li>
<li>S AND THE ENVIRONMENT</li>
<li>SALES AND DISTRIBUTION MGMT</li>
<li>SCENE DESIGN</li>
<li>SCENE RUNNING/CONSTR CREW</li>
<li>SCENERY PRACTICUM</li>
<li>SCIENCE OF OUR PAST</li>
<li>SCIENTIFIC COMPUTING</li>
<li>SCIENTIFIC HPC</li>
<li>SCIENTIFIC METHOD</li>
<li>SCREENWRITING 1</li>
<li>SCREENWRITING 2</li>
<li>SCULPTURE</li>
<li>SECOND LANGUAGE ARABIC</li>
<li>SECOND LANGUAGE CHINESE</li>
<li>SECOND LANGUAGE FRENCH</li>
<li>SECOND LANGUAGE GERMAN</li>
<li>SECOND LANGUAGE ITALIAN</li>
<li>SECOND LANGUAGE JAPANESE</li>
<li>SECOND LANGUAGE LATIN</li>
<li>SECOND LANGUAGE RUSSIAN</li>
<li>SECOND LANGUAGE SPANISH</li>
<li>SECOND YEAR LATIN</li>
<li>SECONDARY STUDENT TEACHING</li>
<li>SECURITY ECONOMICS</li>
<li>SEISMOLOGY</li>
<li>SEM ITALIAN REN ART</li>
<li>SEMICOND DEVICES&amp; CIRCUITS</li>
<li>SEMINAR IN ASIAN HISTORY</li>
<li>SEMINAR IN EARLY MODERN ART</li>
<li>SEMINAR IN INTL STUDIES</li>
<li>SEMINAR IN MUSIC HISTORY</li>
<li>SEMINAR ON MODERN ART</li>
<li>SEMINAR/AMERICAN HISTORY</li>
<li>SEMINAR/EUROPEAN HISTORY</li>
<li>SEMINAR: INTL GOVT &amp; POLITICS</li>
<li>SENIOR DESIGN</li>
<li>SENIOR PROJECT</li>
<li>SENIOR RECITAL</li>
<li>SENIOR SEMINAR</li>
<li>SFTWR TESTNG/QUAL ASSURNC</li>
<li>SHAKESPEARE</li>
<li>SHAKESPEARE AND FILM</li>
<li>SIGHT READING FOR PIANISTS</li>
<li>SIGNAL PROCESS</li>
<li>SINGERS' DICTION REVIEW</li>
<li>SINGLE REED/FLUTE TECHNIQUES</li>
<li>SOCIAL MOVE AND COLL BEHAVIOR</li>
<li>SOCIAL PROBLEMS</li>
<li>SOCIAL PSYCHOLOGY</li>
<li>SOCIAL SCI RESEARCH METHODS</li>
<li>SOCIOLOGICAL PSYCHOLOGY</li>
<li>SOCIOLOGICAL THEORY</li>
<li>SOCIOLOGY</li>
<li>SOFTWARE ENGINEERING PRINCIPLE</li>
<li>SOFTWARE REQUIREMENTS</li>
<li>SOIL MECHANICS AND FOUNDATIONS</li>
<li>SOLAR SYSTEM</li>
<li>SOLID &amp; HAZ WST MGT</li>
<li>SOLID MECHANICS</li>
<li>SOLID STATE DEVICES</li>
<li>SOLO PERFORMANCE</li>
<li>SONGWRITING</li>
<li>SOUND DESIGN AND RECORDING</li>
<li>SOUNDS, &amp; OTHER APPEAR</li>
<li>SOUTH AMERICAN INDIANS</li>
<li>SPACES</li>
<li>SPANISH</li>
<li>SPANISH - ADVANCED</li>
<li>SPANISH - BEGINNING</li>
<li>SPANISH - INTERMEDIATE</li>
<li>SPANISH AS A SECOND LANGUAGE</li>
<li>SPANISH CONVERSATION</li>
<li>SPANISH LINGUISTICS</li>
<li>SPANISH PHONETICS &amp; PHONOLOGY</li>
<li>SPANISH-AM LIT SINCE 1888</li>
<li>SPANISH-AMERICAN CIVILIZATION</li>
<li>SPANISH-AMERICAN NOVEL</li>
<li>SPEC STUDIES:INTERN RELAT</li>
<li>SPEC TOPICS:RELIGIOUS STUDIES</li>
<li>SPECIAL PROJECTS</li>
<li>SPECIAL PROJECTS IN PHYSICS</li>
<li>SPECIAL TOPICS</li>
<li>SPECIAL TOPICS IN ANTHROPOLOGY</li>
<li>SPECIAL TOPICS IN BUSINESS</li>
<li>SPECIAL TOPICS: EARTH SCIENCES</li>
<li>SPECULATIVE MARKETS</li>
<li>SPORT FACILITY AND EVENT MGT</li>
<li>SPORT MANAGEMENT PRACTICUM</li>
<li>SPORTS MANAGEMENT INTERNSHIP</li>
<li>SPORTS MARKETING</li>
<li>SR VOICE RECITAL</li>
<li>STAGE MANAGEMENT 1</li>
<li>STAGE MGMT</li>
<li>STAGE PHOTOGRAPHY</li>
<li>STAT METHODS FOR ENGINEERS</li>
<li>STAT MTHDS FOR ENG &amp; APPD SC</li>
<li>STATE AND LOCAL GOVERNMENT</li>
<li>STATEGIC COMM &amp; PR - ADVANCED</li>
<li>STATICS</li>
<li>STATISTICAL METHODS</li>
<li>STATISTICAL METHODS IN EE</li>
<li>STATISTICS</li>
<li>STATISTICS FOR BUSINESSI DECISIONS</li>
<li>STATISTICS FOR ENGINEERS</li>
<li>STATS FOR ENGR/SCIENTISTS</li>
<li>STOCHASTIC MODELS IN OR</li>
<li>STRATEGIC BEHAVIOR</li>
<li>STRATEGIC COMMUNICATION AND PR</li>
<li>STRATEGIC MGMT IN A GLOBAL ECO</li>
<li>STRING PEDAGOGY</li>
<li>STRUCTURAL ANALYSIS</li>
<li>STRUCTURAL DYNAMICS</li>
<li>STUDIES IN CREATIVE WRITING</li>
<li>STUDIES IN MEDIEVAL LITERATURE</li>
<li>STUDIES IN MODERN AMERICAN LIT</li>
<li>SUCCESS STRATEGIES</li>
<li>SURVEY ELECTRICAL&amp; ELECTRONIC</li>
<li>SURVEY OF ADVERTISING</li>
<li>SURVEY OF MUSIC HISTORY</li>
<li>SURVEY OF MUSIC PSYCHOLOGY</li>
<li>SURVEY OF OPERA HISTORY</li>
<li>SUSTAINABILITY</li>
<li>SYSTEMS ANALYSIS METHODS</li>
<li>SYSTEMS ARCHITECTURE DEVELOPMT</li>
<li>SYSTEMS ENGINEERING LEADERSHIP</li>
<li>SYSTMS ENGINEERNG PROCESS</li>
<li>SYZYGY</li>
<li>TALKING AND WRITING IN GERMAN</li>
<li>TEACHING MATH IN ELEM SCHOOL</li>
<li>TEACHING PRACTICUM</li>
<li>TECH 4: SOUND</li>
<li>TECH 5: LTG AUTOMATION</li>
<li>TECHNICAL ENTREPRENEURSHIP</li>
<li>TECHNIQUE ELECTIVE - ADVANCED</li>
<li>TECHNIQUES OF VOCAL ACCOM</li>
<li>TEXAS POLITICS</li>
<li>THEA, DRAMA, PERF</li>
<li>THIRD-YEAR JAPANESE</li>
<li>TION POLITICAL THEORY</li>
<li>TION TO ELECTRO THEORY</li>
<li>TIONS &amp; THEIR ENVIRON</li>
<li>TOPICS</li>
<li>TOPICS IN ADVERTISING</li>
<li>TOPICS IN COMMUNICATION</li>
<li>TOPICS IN COMMUNICATIONS</li>
<li>TOPICS IN DIGITAL SIGNAL PROC</li>
<li>TOPICS IN JOURNALISM</li>
<li>TOPICS IN MEDIA INDUSTRIES</li>
<li>TOPICS IN PHILOSOPHY - ADVANCED</li>
<li>TOPICS IN SPANISH CIVILIZATION</li>
<li>TOPICS-FILM AND MEDIA STUDIES</li>
<li>TOXICOLOGY WITH</li>
<li>TRANS-ATLANTIC STUDIES</li>
<li>TRE PRACTICUM</li>
<li>TUTORIAL FOR JRS + SRS</li>
<li>ULE THE WORLD</li>
<li>UNDERGRADUATE FT STATUS</li>
<li>UNDERGRADUATE INTERNSHIP</li>
<li>UNFINISHED NATION:US 1877-PRES</li>
<li>UPPER STRING TECHNIQUES</li>
<li>VEHICLE DYNAMICS</li>
<li>VIBRATIONS</li>
<li>VIETNAM: AMERICA'S WAR</li>
<li>VLSI DESIGN AND</li>
<li>VOCAL COACHING</li>
<li>VOCAL PEDAGOGY</li>
<li>VOCAL TECHNIQUES</li>
<li>WARFARE AND VIOLENCE</li>
<li>WASHINGTON TERM</li>
<li>WAYS OF BEING RELIGIOUS</li>
<li>WEALTH AND CONSUMPTION</li>
<li>WESTERN RELIGIONS</li>
<li>WHOLENESS&amp;HOLINESS:RELIG</li>
<li>WOMEN IN US HISTORY TO 1900</li>
<li>WOMEN'S POINTE TECHNIQUE</li>
<li>WORD AND IMAGE</li>
<li>WORLD MUSIC ENSEMBLE</li>
<li>WORLD OF SHAKESPEARE</li>
<li>WRITING AND EDITING</li>
<li>YOGA FOR DANCERS</li>
<li>ZOOARCHAEOLOGY</li>
</ul>
